#!/bin/sh
echo LowIntensity2.5hour_Slave0Chip0.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip1.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip2.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip3.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip4.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip5.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip6.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip7.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip8.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip9.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip10.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip11.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip12.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip13.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip14.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave0Chip15.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip0.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip1.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip2.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip3.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip4.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip5.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip6.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip7.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip8.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip9.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip10.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip11.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip12.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip13.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip14.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave1Chip15.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip0.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip1.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip2.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip3.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip4.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip5.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip6.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip7.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip8.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip9.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip10.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip11.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip12.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip13.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip14.dat | python3 ChannelPairBuilder.py
echo LowIntensity2.5hour_Slave2Chip15.dat | python3 ChannelPairBuilder.py
cd /home/kilroy101/Experimental_Data/TPPT_DATA/Scanner_Commissioning/Threshold_Optimization/LowIntensity2.5hour_SPLIT
cat Output_LowIntensity2.5hour_Slave* >> Output_LowIntensity2.5hour.csv
